/* IMPORTANT
 * This snapshot file is auto-generated, but designed for humans.
 * It should be checked into source control and tracked carefully.
 * Re-generate by setting TAP_SNAPSHOT=1 and running tests.
 * Make sure to inspect the output below.  Do not ignore changes!
 */
'use strict'
exports[`src/sladd.test.js TAP sladdHtml(Mata Hari) > must match snapshot 1`] = `
Object {
  "redactedText": "<h1><span><redacted-word data-word-id=\\"0\\" data-length=\\"4\\"></redacted-word> <redacted-word data-word-id=\\"1\\" data-length=\\"4\\"></redacted-word></span></h1><p><b><redacted-word data-word-id=\\"2\\" data-length=\\"10\\"></redacted-word> <redacted-word data-word-id=\\"3\\" data-length=\\"10\\"></redacted-word> <redacted-word data-word-id=\\"4\\" data-length=\\"5\\"></redacted-word></b> (<redacted-word data-word-id=\\"5\\" data-length=\\"4\\"></redacted-word> <redacted-word data-word-id=\\"6\\" data-length=\\"1\\"></redacted-word>. <redacted-word data-word-id=\\"7\\" data-length=\\"6\\"></redacted-word> <redacted-word data-word-id=\\"8\\" data-length=\\"4\\"></redacted-word> i <redacted-word data-word-id=\\"9\\" data-length=\\"10\\"></redacted-word>, <redacted-word data-word-id=\\"10\\" data-length=\\"9\\"></redacted-word>, <redacted-word data-word-id=\\"11\\" data-length=\\"3\\"></redacted-word> <redacted-word data-word-id=\\"12\\" data-length=\\"2\\"></redacted-word>. <redacted-word data-word-id=\\"13\\" data-length=\\"7\\"></redacted-word> <redacted-word data-word-id=\\"14\\" data-length=\\"4\\"></redacted-word> <redacted-word data-word-id=\\"15\\" data-length=\\"9\\"></redacted-word>, <redacted-word data-word-id=\\"16\\" data-length=\\"9\\"></redacted-word>), <redacted-word data-word-id=\\"17\\" data-length=\\"5\\"></redacted-word> under <redacted-word data-word-id=\\"18\\" data-length=\\"14\\"></redacted-word> <b><redacted-word data-word-id=\\"19\\" data-length=\\"4\\"></redacted-word> <redacted-word data-word-id=\\"20\\" data-length=\\"4\\"></redacted-word></b>, var en <redacted-word data-word-id=\\"21\\" data-length=\\"11\\"></redacted-word> <redacted-word data-word-id=\\"22\\" data-length=\\"6\\"></redacted-word> og <redacted-word data-word-id=\\"23\\" data-length=\\"7\\"></redacted-word> <redacted-word data-word-id=\\"24\\" data-length=\\"5\\"></redacted-word>. Hun <redacted-word data-word-id=\\"25\\" data-length=\\"6\\"></redacted-word> hun var en <redacted-word data-word-id=\\"26\\" data-length=\\"10\\"></redacted-word> <redacted-word data-word-id=\\"27\\" data-length=\\"9\\"></redacted-word>. I <redacted-word data-word-id=\\"28\\" data-length=\\"4\\"></redacted-word> <redacted-word data-word-id=\\"29\\" data-length=\\"5\\"></redacted-word> hun i <redacted-word data-word-id=\\"30\\" data-length=\\"9\\"></redacted-word> der hun var <redacted-word data-word-id=\\"31\\" data-length=\\"4\\"></redacted-word> med <redacted-word data-word-id=\\"32\\" data-length=\\"10\\"></redacted-word> og <redacted-word data-word-id=\\"33\\" data-length=\\"9\\"></redacted-word> fra <redacted-word data-word-id=\\"34\\" data-length=\\"5\\"></redacted-word> <redacted-word data-word-id=\\"35\\" data-length=\\"5\\"></redacted-word> i <redacted-word data-word-id=\\"36\\" data-length=\\"6\\"></redacted-word>, før hun i <redacted-word data-word-id=\\"37\\" data-length=\\"2\\"></redacted-word>. <redacted-word data-word-id=\\"38\\" data-length=\\"7\\"></redacted-word> <redacted-word data-word-id=\\"39\\" data-length=\\"4\\"></redacted-word> ble <redacted-word data-word-id=\\"40\\" data-length=\\"9\\"></redacted-word> og <redacted-word data-word-id=\\"41\\" data-length=\\"2\\"></redacted-word>. <redacted-word data-word-id=\\"42\\" data-length=\\"7\\"></redacted-word> ble <redacted-word data-word-id=\\"43\\" data-length=\\"9\\"></redacted-word> ved <redacted-word data-word-id=\\"44\\" data-length=\\"7\\"></redacted-word> i <redacted-word data-word-id=\\"45\\" data-length=\\"9\\"></redacted-word>. Det har <redacted-word data-word-id=\\"46\\" data-length=\\"6\\"></redacted-word> <redacted-word data-word-id=\\"47\\" data-length=\\"5\\"></redacted-word> <redacted-word data-word-id=\\"48\\" data-length=\\"9\\"></redacted-word> om hun <redacted-word data-word-id=\\"49\\" data-length=\\"8\\"></redacted-word> var <redacted-word data-word-id=\\"50\\" data-length=\\"5\\"></redacted-word> eller ikke, og det er også <redacted-word data-word-id=\\"51\\" data-length=\\"5\\"></redacted-word> <redacted-word data-word-id=\\"52\\" data-length=\\"7\\"></redacted-word> at hun var <redacted-word data-word-id=\\"53\\" data-length=\\"11\\"></redacted-word>.</p>",
  "words": Array [
    "Mata",
    "Hari",
    "Margaretha",
    "Geertruida",
    "Zelle",
    "født",
    "7",
    "august",
    "1876",
    "Leeuwarden",
    "Nederland",
    "død",
    "15",
    "oktober",
    "1917",
    "Vincennes",
    "Frankrike",
    "kjent",
    "kunstnernavnet",
    "Mata",
    "Hari",
    "nederlandsk",
    "danser",
    "påstått",
    "spion",
    "hevdet",
    "javanesisk",
    "prinsesse",
    "1914",
    "bodde",
    "Frankrike",
    "venn",
    "politikere",
    "offiserer",
    "begge",
    "sider",
    "krigen",
    "13",
    "februar",
    "1917",
    "arrestert",
    "15",
    "oktober",
    "henrettet",
    "skyting",
    "Vincennes",
    "senere",
    "blitt",
    "diskutert",
    "virkelig",
    "spion",
    "blitt",
    "påstått",
    "kontraspion",
  ],
}
`
